#!/bin/bash

CURRENT_USER=$(getent passwd 1000 | cut -d: -f1)

if [ -z "${CURRENT_USER}" ]; then
    exit 1
fi

HOME_DIR="/home/${CURRENT_USER}"
WORKSPACE_DIR="/vol1/1000/coderProject"


sudo mkdir -p "${HOME_DIR}" "${WORKSPACE_DIR}"
sudo chown -R "${CURRENT_USER}:1001" "${HOME_DIR}" "${WORKSPACE_DIR}"
sudo chmod 755 "${HOME_DIR}"

exit 0