#!/bin/bash

CURRENT_USER=$(getent passwd 1000 | cut -d: -f1)

if [ -z "${CURRENT_USER}" ]; then
    exit 1
fi

HOME_DIR="/home/${CURRENT_USER}"
WORKSPACE_DIR="/vol1/1000/VscodeProject"

sudo mkdir -p "${HOME_DIR}" "${WORKSPACE_DIR}"
sudo ln -sfn "${WORKSPACE_DIR}" "${HOME_DIR}/project"
sudo chown -R "${CURRENT_USER}:Users" "${HOME_DIR}" "${WORKSPACE_DIR}"
sudo chmod 700 "${HOME_DIR}"

exit 0