#!/bin/bash
REQUEST_IP=$(hostname -I | awk '{print $1}')

sudo tee "/etc/systemd/system/code-server.service" > /dev/null <<EOF
[Unit]
Description=code-server
After=network.target
[Service]
Type=simple
User=1000
Group=1001
ExecStart=/opt/code-server/bin/code-server \
    --config /var/apps/coder/shares/data/config.yaml \
    --user-data-dir /var/apps/coder/var/data \
    --bind-addr ${REQUEST_IP}:8080 --auth password

Restart=always
[Install]
WantedBy=multi-user.target
EOF
 
# 启动服务
sudo systemctl restart code-server
sudo systemctl enable code-server

exit 0