#!/bin/bash
LOG_FILE="${TRIM_PKGVAR}/info.log"
INSTALL_TARGETDIR="/opt/code-server"
CODER_WORKSPACEDIR="/vol1/1000/VscodeProject"

#获取处理器架构
ARCH=""
case "${TRIM_SYS_ARCH}" in
    x86_64|x86)
        ARCH="amd64"
        ;;
    aarch64|arm)
        ARCH="arm64"
        ;;
    armv7l|armv7)
        ARCH="armv7l"
        ;;
    *)
        log_msg "不支持的架构: $TRIM_SYS_ARCH"
        exit 1
        ;;
esac

### This script is called after the user installs the application.
log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

patch_product_json() {
    if ! command -v jq >/dev/null 2>&1; then
        log_msg "jq 未安装，请先安装 jq"
        return 1
    fi

    local FILE_PATH="${CODER_WORKSPACEDIR}/code-server/lib/vscode/product.json"
    jq '
        .linkProtectionTrustedDomains = [
        "https://open-vsx.org",
        "https://marketplace.visualstudio.com"
        ]
        |
        .extensionsGallery = {
        "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
        "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
        "itemUrl": "https://marketplace.visualstudio.com/items",
        "controlUrl": "",
        "recommendationsUrl": ""
        }
    ' "$FILE_PATH" > /tmp/product.json.tmp && \
    mv /tmp/product.json.tmp "$FILE_PATH"
}

download_latest() {
    local LATEST_VERSION
    log_msg "正在获取最新版本信息..."
    LATEST_VERSION=$(curl -s https://api.github.com/repos/coder/code-server/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
    if [ -z "$LATEST_VERSION" ]; then
        log_msg "获取版本失败，请检查网络。"
        return 1
    fi
    local DICT_FILE="code-server-${LATEST_VERSION}-linux-${ARCH}.tar.gz"
    log_msg "最新版本为: $LATEST_VERSION，准备下载: ${DICT_FILE}"

    local DICT_URL="https://github.com/coder/code-server/releases/download/v${LATEST_VERSION}/${DICT_FILE}"
    wget -c "$DICT_URL" --show-progress || {
        log_msg "下载失败"
        return 1
    }
    log_msg "最新版本下载完成: ${CODER_WORKSPACEDIR}/$DICT_FILE"

    return 0
}


log_msg "开始安装 code-server"

cd $CODER_WORKSPACEDIR || {
    log_msg "无法进入 ${CODER_WORKSPACEDIR}"
    exit 1
}

files=("$CODER_WORKSPACEDIR"/code-server-*-linux-${ARCH}.tar.gz)

if [ -e "${files[0]}" ]; then
    log_msg "发现压缩包: ${files[0]}"
else
    log_msg "目录中没有 code-server 压缩包"
    download_latest || {
        log_msg "下载最新版本失败"
        exit 1
    }
fi

log_msg "正在解压文件..."
tar -xzf code-server-*-linux-${ARCH}.tar.gz || {
    log_msg "解压失败"
    exit 1
}
mv code-server-*-linux-${ARCH} code-server 
patch_product_json
rm code-server-*-linux-${ARCH}.tar.gz

log_msg "解压完成，正在移动文件到：$INSTALL_TARGETDIR..."
sudo mv code-server "$INSTALL_TARGETDIR" || {
    log_msg "移动文件失败"
    exit 1
}
sudo ln -s /opt/code-server/bin/code-server /usr/local/bin/coder


# 配置code-server文件
CONFIG_FILE="/var/apps/coder/etc/config.yaml"
cat > "$CONFIG_FILE" <<EOF
bind-addr: 0.0.0.0:${wizard_port}
auth: password
password: ${wizard_password}
cert: false
EOF

log_msg "正在创建 systemd 服务文件..."
sudo tee "/etc/systemd/system/code-server.service" > /dev/null <<EOF
[Unit]
Description=code-server
After=network.target
[Service]
Type=simple
Restart=always
ExecStart=/opt/code-server/bin/code-server \
    --config /var/apps/coder/etc/config.yaml \
    --user-data-dir /var/apps/coder/var/data
User=1000
Group=1001
[Install]
WantedBy=multi-user.target
EOF

# 启动服务
sudo systemctl restart code-server
sudo systemctl enable code-server

log_msg "code-server 安装完成。"

exit 0